[project]
name = "bioeq"
version = "0.1.0"
description = "A Python package for performing bioequivalence calculations and analysis."
readme = "README.md"
authors = [
    { name = "Shaun Porwal", email = "shaun.porwal@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
