name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  # Run tests for Python 3.11
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install Tox
      - name: Install Tox
        run: pip install tox

      # Run Tox Tests
      - name: Run Tests
        run: tox -e py311

  # Code formatting check with black
  format:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install Tox
      - name: Install Tox
        run: pip install tox

      # Run Formatting Check
      - name: Run Formatting Check
        run: tox -e format
