permissions:
  contents: write

name: Generate Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocstrings[python] mkdocs
          pip install -e .

      - name: Create docs structure
        run: |
          mkdir -p docs
          cat > docs/index.md << 'EOF'
          # BioEQ Documentation

          ## API Documentation

          ::: bioeq
              options:
                members: false
                show_submodules: true
          EOF
          cat > mkdocs.yml << 'EOF'
          site_name: BioEQ
          theme:
            name: material
          plugins:
            - search
            - mkdocstrings:
                handlers:
                  python:
                    options:
                      filters:
                        - "!^_[^_]"
                        - "!^__all__$"
                        - "!^__version__$"
                      group_by_category: true
                      members_order: alphabetical
          EOF

      - name: Build docs
        run: mkdocs build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
